#!/usr/bin/env bash
# THE INSIGHTS VIEW, driven: every key it claims, at three heights.
#
# Assertions on captures rather than byte goldens, and that is not laziness:
# the screen's title carries today's date and its periods are "today" and
# "this week", so a golden taken on Tuesday would fail on Wednesday. The
# ledger is generated by mkledger.py against today for the same reason.
# What the FIGURES say is tests/test_stats.py's subject (hand-computed, from
# rows); what this file proves is that the screen draws them, that every key
# does what the footer says, and that nothing is clipped.
#
# Nothing here reads a real transcript, a real ledger or the real config: the
# sandbox owns HOME, XDG_*, MUXTOPUS_CONFIG and CLAUDE_CONFIG_DIR, and its
# tmux is pinned to -L mxsplit by bin/tmux.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/env.sh"

CAPS="${SB:?}/caps-insights"
rm -rf -- "${CAPS:?}"; mkdir -p -- "${CAPS:?}"
"$HERE/clean.sh"

K="$HERE/k.sh"; C="$HERE/cap.sh"
STATS="${SB:?}/state/muxtopus/stats-mxsplit"
OTHER="${SB:?}/state/muxtopus/stats-other"
EXPORTS="${SB:?}/muxhome/exports"
PRICES="${SB:?}/config/muxtopus/prices.md"
fails=0; checks=0

ok()   { checks=$((checks + 1)); }
bad()  { echo "FAIL: $*" >&2; fails=$((fails + 1)); checks=$((checks + 1)); }

shot() {   # shot <name> <substring the screen must contain>
  "$C" > "${CAPS:?}/$1.txt"
  if grep -qF -- "$2" "${CAPS:?}/$1.txt"; then ok; else
    bad "$1 does not contain '$2'"
    grep -v '^$' "${CAPS:?}/$1.txt" | tail -14 >&2
  fi
}

absent() { # absent <name> <substring the screen must NOT contain>
  if grep -qF -- "$2" "${CAPS:?}/$1.txt"; then bad "$1 still contains '$2'"; else ok; fi
}

fits() {   # fits <name>  -- the footer is still the bottom of the frame
  # capture-pane always returns exactly as many lines as the pane is tall, so
  # "did it fit" has to be asked the other way round: Live crops a too-tall
  # frame from the BOTTOM, so the footer's last key is what goes missing
  # first. If "q quit" is on the last non-blank line, nothing was cropped.
  local last; last="$(grep -v '^$' "${CAPS:?}/$1.txt" | tail -2)"
  case "$last" in *"q quit"*) ok ;;
    *) bad "$1: the footer is not at the bottom -- the frame was cropped" ;; esac
}

ledger() { python3 "$HERE/mkledger.py" "$@" >/dev/null || bad "mkledger $*"; }

# ===================================================== 1. the full screen
rm -rf -- "${STATS:?}" "${OTHER:?}" "${EXPORTS:?}"
rm -f -- "${PRICES:?}"
ledger "${STATS:?}"
ledger "${OTHER:?}" --seed 21 --scale 0.4 --days 25

"$HERE/start.sh" 58 >/dev/null
$K i
sleep 1.5                               # the collect on open runs on a thread
shot insights-open        "insights"
shot insights-rows        "TOKENS"
absent insights-rows      "failed to load"
for row in CACHE COST CONTEXT SESSIONS BUDGET LANES RHYTHM; do
  if grep -q "│ $row" "${CAPS:?}/insights-rows.txt"; then ok
  else bad "the $row row is missing"; fi
done
shot insights-breakdown   "by project"
shot insights-since       "collecting since"
# NO PRICE FILE: tokens only, and it says so rather than guessing a number.
shot insights-noprices    "no price"
fits insights-open

# ------------------------------------------------------ prices turn $ on
cp -- "${SCRIPTS:?}/seeds/prices.md" "${PRICES:?}"
$K r                                    # r recollects and re-reads the ledger
sleep 4
shot insights-priced      "API-equiv"
absent insights-priced    "no price file"

# ----------------------------------------------------------- the periods
$K Right; shot period-last7   "last 7 d"
$K Right; shot period-month   "this month"
$K Left;  shot period-back    "last 7 d"
$K Left;  shot period-week    "this week"
$K Left;  shot period-today   "today"
$K Right; shot period-rewound "this week"

# ---------------------------------------------------------- the grouping
$K g;     shot group-model    "by model"
shot group-model-rows         "claude-opus-5"
$K g;     shot group-lane     "by lane"
$K G;     shot group-back     "by model"

# ------------------------------------------------------- drill and climb
$K Enter; shot drill-sessions "by session"
shot drill-filter             "model claude-"
$K Enter; shot drill-days     "by day"
$K Enter; shot drill-leaf     "as deep as it goes"
$K BSpace; shot climb-sessions "by session"
$K BSpace; shot climb-model   "by model"
absent climb-model            "model claude-"
$K BSpace; shot climb-top     "at the top"

# --------------------------------------------------------- f, F, and the
# multi-step picker: a dimension, then a value that is IN the ledger.
$K f;     shot filter-dims    "filter by"
shot filter-dims-list         "main / subagent"
$K Enter; shot filter-values  "filter · project"
shot filter-values-any        "(any"
$K Down; $K Down; $K Enter
shot filter-applied           "project ~/"
$K F;     shot filter-cleared "all projects"

# ------------------------------------------------- a: every account's ledger
$K a;     shot accounts-all   "2 account(s)"
$K a;     shot accounts-mine  "this account"

# ----------------------------------------------------------- e: the export
$K e; sleep 0.8
shot export-said              "exported"
n="$(ls -1 "${EXPORTS:?}" 2>/dev/null | wc -l)"
[ "$n" = 3 ] && ok || bad "export wrote $n file(s), wanted 3 (.md, .csv, .json)"
f="$(ls -1 "${EXPORTS:?}"/*.json 2>/dev/null | head -1)"
python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert d['tokens']['total']>0; assert d['group_by']" \
  "$f" 2>/dev/null && ok || bad "the exported .json does not parse or has no figures"
f="$(ls -1 "${EXPORTS:?}"/*.csv 2>/dev/null | head -1)"
python3 -c "import csv,sys; r=list(csv.reader(open(sys.argv[1]))); assert len(r)>1, r; assert r[0][1]=='tokens'" \
  "$f" 2>/dev/null && ok || bad "the exported .csv does not parse"
grep -q "API-equivalent" "$(ls -1 "${EXPORTS:?}"/*.md | head -1)" && ok \
  || bad "the exported .md has no 'API-equivalent' note"

# -------------------------------------------- esc goes back, i comes back
$K Escape; shot left-to-main  "claude [mxsplit]"
$K i;      shot back-again    "insights"
# The view keeps its question between visits: still by model, not reset.
shot back-again-kept          "by model"
$K Escape >/dev/null

# ------------------------------------------- the row it adds to the esc menu
$K Escape; shot mux-has-insights "Insights ▸"
# It is UNDER the two switches: the route's Down-from-Settings must still
# land on Watchdog, so this row may not sit between them.
$K Down;   shot mux-first-down   "Watchdog"
if grep -q '▸ *Watchdog' "${CAPS:?}/mux-first-down.txt"; then ok
else bad "the first Down in the esc menu no longer lands on Watchdog"; fi
$K Down; $K Down
$K Enter; sleep 0.6
shot mux-row-opens            "insights"
$K Escape >/dev/null

"$HERE/stop.sh" >/dev/null 2>&1

# ============================================ 2. the short terminals
for H in 24 40; do
  "$HERE/start.sh" "$H" >/dev/null
  $K i
  shot "h$H-open"       "TOKENS"
  shot "h$H-table"      "by project"
  fits "h$H-open"
  # The table scrolls inside what is left rather than pushing the frame off
  # the bottom. It needs more rows than the panel has, so: every day ever,
  # which is forty of them, against a table that has at most twenty-five.
  $K Right; $K Right; $K Right; $K Right   # week -> last7 -> month -> last30 -> all
  $K g; $K g; $K g                         # by project -> model -> lane -> day
  shot "h$H-day"        "by day"
  shot "h$H-all"        "◂ all ▸"
  fits "h$H-day"
  if grep -q "more" "${CAPS:?}/h$H-day.txt"; then ok
  else bad "h$H: a 40-day breakdown drew no ▲/▼ marker on a $H-row terminal"; fi
  $K Down; $K Down; $K Down; $K Down
  shot "h$H-scrolled"   "by day"
  fits "h$H-scrolled"
  "$HERE/stop.sh" >/dev/null 2>&1
done

# ================================================ 3. the day-one screen
rm -rf -- "${STATS:?}"
ledger "${STATS:?}" --empty
"$HERE/start.sh" 40 >/dev/null
$K i
shot dayone           "nothing collected yet"
shot dayone-title     "insights"
absent dayone         "Traceback"
fits dayone
"$HERE/stop.sh" >/dev/null 2>&1

echo
if [ "$fails" = 0 ]; then
  echo "insights: $checks checks passed"
else
  echo "insights: $fails of $checks checks FAILED"
fi
exit "$((fails > 0))"
